### PR TITLE
add minZoom and maxZoom parameters

### PR DESCRIPTION
**Pull request by diachedelic**
it does not automatically reset bounds at min but it's a start

### CODE REVIEW

**Comment by anitasv** [comment]
Looks like this will only put a limit to each individual zoom, but objective is setting overall maximum zoom.

**Comment by diachedelic** [comment]
pretty sure it limits overall zoom, did you try it?

**Comment by diachedelic** [comment]
@anitasv just to clarify, I do believe this PR limits overall zoom, not just each individual zoom

**Comment by anitasv** [comment]
Hi, i will test it soon, didn't get time.

**Comment by anitasv** [comment]
looks good.

**Comment by anitasv** [comment]
Hi there were some more issues like rotation zoom was not correct, and local zoom shouldn't clamp based on minMax, the clamping must be on the output. I fixed all these issues

https://github.com/anitasv/zoom/pull/37

**Comment by diachedelic** [comment]
Ah ok. What do you mean by "local zoom"?

**Pull request closed without merging**
